### ISSUE TITLE
Add ability to configure view

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#11]
I need ability for some demos to have objects expanded by default on some depth if there is more less than provided value of fields. It should look like:
```js
var jsConsole = jsConsoleInit(document.querySelector('.console-container'), {
  autoExpandFields: 4, 
  autoExpandDepth: 2
});
```

**Comment by nikolayemrikh** [comment]
Ok, i’all look it up today

**Comment by nikolayemrikh** [comment]
@zeckson it's done. Check readme
