### ISSUE TITLE
Add collapse/expand element

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#17]
![image](https://user-images.githubusercontent.com/259739/38141980-4a2fb696-3443-11e8-83db-b46516c77687.png)
Currently it's not clear what I have to do to expand structure or object, let's add some graphical element for expand/collapse. Like there:
![image](https://user-images.githubusercontent.com/259739/38142031-78bbb80c-3443-11e8-98c8-fc1320f2d49e.png)

**Comment by nikolayemrikh** [comment]
Ok

**Comment by nikolayemrikh** [comment]
@zeckson готово, задеплоено
