### ISSUE TITLE
Invalid expand configuration 

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#19]
I configured arrays with this autoexpand configuration:
```js
{
      'array': {
        expandDepth: 2, // expand 2 levels
        maxFieldsInHead: 4,
      }
}
```
So I assumed it will expand only arrays smaller than 4 elements inside. But it's not.
![image](https://user-images.githubusercontent.com/259739/38415317-cf9530bc-3999-11e8-993a-fc7e9f4128a4.png)

**Comment by nikolayemrikh** [comment]
maxieldsInHead is option only available to object config yet. And it’s not influences on triggering expand.

**Comment by nikolayemrikh** [comment]
@zeckson What you want is minFieldsToExpant. Check readme
