### ISSUE TITLE
logHTML method

### ISSUE THREAD

**Issue by nikolayemrikh** [htmlacademy/console.js#26]
Hey, @zeckson, I’m currently working on adding this method and i have some questions.

Do we need not escape HTML only on 1 depth level? (console.log(“\<strong\>bold\<\/strong\>”);)

Or on other depth levels too?
console.log({str: “\<strong\>bold\<\/strong\>”});
If so, should not escape only in opened form or inside header too?

**Comment by zeckson** [comment]
All levels should be not escaped
