### ISSUE TITLE
Скрывать stacktrace по умолчанию

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#28]
По умолчанию `stacktrace` к ошибкам должен быть свёрнут
![image](https://user-images.githubusercontent.com/259739/40610913-e2d468bc-627c-11e8-8b71-eadc35b03097.png)

**Comment by nikolayemrikh** [comment]
@zeckson сделаю это не по умолчанию, а засуну в пресет htmlacademy.js, пойдёт?

**Comment by zeckson** [comment]
@nikolayemrikh да вроде хорошее умолчанию. В хроме же оно вроде как свёрнуто по умолчанию.

**Comment by nikolayemrikh** [comment]
@zeckson хм 🤔
<img width="1280" alt="2018-05-28 13 55 15" src="https://user-images.githubusercontent.com/11134770/40611440-fc380834-627e-11e8-9cd7-eb95be852a73.png">

**Comment by nikolayemrikh** [comment]
В хроме как раз по умолчанию стек показан

**Comment by zeckson** [comment]
Всё равно мне кажется это хорошим решением =)

**Comment by nikolayemrikh** [comment]
Ок, давай сделаем так

**Comment by nikolayemrikh** [comment]
fixed
