### ISSUE TITLE
Add info about default available presets, examples and usages

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#29]
Currently there is no info about default presets in `Readme.md` it would be great if I could copy and paste some good default presets and take a look what these presets are about.

**Comment by nikolayemrikh** [comment]
Могу предложить сейчас такой конфиг:

```js
{
  function: {
    nowrapOnLog: true
  },
  common: {
    excludeProperties: [`__proto__`],
    maxFieldsInHead: 5,
    minFieldsToExpand: 5,
    maxFieldsToExpand: 15,
    expandDepth: 1
  }
}
```

Как ты просил `function.nowrapOnLog` коллапсит строки функции в одну.

При автораскрытии исключается поле `__proto__`.
Раскрываются все объекты (`common`) на глубину 1 (`expandDepth`)) при условии, что объект содержит от 5 до 15 полей (`minFieldsToExpand`, `maxFieldsToExpand`)

В хедере показываются только 5 полей (`maxFieldsInHead`).
Считаются только поля с ключами, для массивов в хедере ключи  не показываются, поэтому эта настройка на них не повлияет. Если нужно ограничивать и количество полей в хедере массива, нужно задать `array.countEntriesWithoutKeys = true`

Поведение по-умолчанию (как в браузере)

<img width="1242" alt="2018-05-28 14 59 43" src="https://user-images.githubusercontent.com/11134770/40613684-3a546c4e-6288-11e8-80ad-b90a6b9b3f54.png">

И при заданном `array.countEntriesWithoutKeys = true`

<img width="1115" alt="2018-05-28 15 02 28" src="https://user-images.githubusercontent.com/11134770/40613688-439b3d14-6288-11e8-8783-b027560a59c3.png">

**Comment by nikolayemrikh** [comment]
Так же можно указать, какие типы вьюх исключить при автораскрытии (array, function, object). Либо наоборот, указать какие именно открывать.

Можно даже указать, что хотим исключить, например, автораскрытие объекта внутри другого автоматом раскрытого рутового объекта

**Comment by zeckson** [comment]
Просто бомбически! Это `preset/htmlacademy.js`?

**Comment by nikolayemrikh** [comment]
@zeckson да)

**Comment by nikolayemrikh** [comment]
`countEntriesWithoutKeys` добавить туда?

**Comment by zeckson** [comment]
А почему при нём меньше элементов стало у тебя на скриншоте — 1479 против 932?

**Comment by nikolayemrikh** [comment]
@zeckson страница другая, скрин первый нечайно сделал на странице github.io, поменял кого-то, понял, что не там, открыл локалхост

**Comment by zeckson** [comment]
а я правильно понимаю, что он показывает `empty` в массиве если элемент удалён?

**Comment by nikolayemrikh** [comment]
Идёт цикл от 0 до длины массива

Если нет поля с ключом для индекса в этом диапазоне – показывает empty

**Comment by zeckson** [comment]
А, не, давай не будем. Будет же втыкать на больших массивах.

**Comment by nikolayemrikh** [comment]
Не будем что?

**Comment by nikolayemrikh** [comment]
А, добавлять countEntriesWithoutKeys: true?

Тогда получается наоборот давай будем, чтоб не показывало такое полотно. Ибо он как раз тримает лишнее, если это поле - true. 

Если я тебя правильно понял

**Comment by zeckson** [comment]
Я запутался =( *хнык*
