### ISSUE TITLE
Add ability to show methods expanded

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#38]
![image](https://user-images.githubusercontent.com/259739/41159879-ae046fc0-6b36-11e8-8bac-5a047e45bc3b.png)

**Comment by nikolayemrikh** [comment]
Справа скрин старой консоли. Объясни подробнее, что нужно?
Методы функции можно увидеть, только если использовать console.dir

**Comment by nikolayemrikh** [comment]
console.log/info выводят тело функции как есть

**Comment by nikolayemrikh** [comment]
Догнал

**Comment by nikolayemrikh** [comment]
Посмотрю, как можно это совместить с текущими реалиями (и тем, как сделано в хроме)

**Comment by zeckson** [comment]
Поле подойтёт. Я просто настрою демку правильно

**Comment by nikolayemrikh** [comment]
Ты хочешь вообще без пресетов демку оформить? Или подключать этот общий пресет, а потом ещё руками докинуть поле по аналогии, как в коде пресета?

**Comment by nikolayemrikh** [comment]
Я кстати там исправлял ридми, но так и не вмержил. В другой ветке лежит

**Comment by zeckson** [comment]
мне это пока только для этой демки нужно, поэтому я готов на любой вариант =)

**Comment by nikolayemrikh** [comment]
Можешь вообще описать сейчас ситуацию с консолью? Планируешь все перевести со старой на новую?

**Comment by zeckson** [comment]
я давно хочу перевести на новую, но были проблемы раньше. Сейчас просто нет времени снова пройтись и проверить, что демки которые я не заменил не деградируют на новой консоле

**Comment by zeckson** [comment]
В `ecma` всего 2-3 демки на старой консоле остались. Вот из-за похожих проблем как в этой ишшье

**Comment by nikolayemrikh** [comment]
Напиши, какие посмотреть, может? И желаемый результат

**Comment by zeckson** [comment]
написал в ЛС

**Comment by nikolayemrikh** [comment]
<img width="1108" alt="2018-11-09 0 14 48" src="https://user-images.githubusercontent.com/11134770/48227832-82084a80-e3b4-11e8-8613-2847e8ad59d2.png">

**Comment by zeckson** [comment]
О круто!
2 вопроса:
1. Можем ли мы избавиться от `условия`:
```
if (Array.isArray(...)) {
...
```
Кажется что это какая-то твоя внутренняя кухня о которой мне знать не нужно. Всё что я хочу — это просто применить настройки.

2. Почему справа вывод выглядит по разному?
В первом случае метод из 3х строк во втором однострочный

**Comment by nikolayemrikh** [comment]
1. Хз, когда я это придумывал, на то было основание (вроде)
2. Я сам открыл для наглядности. В реальности обе будут открыты/закрыты в зависимости от настроек

**Comment by nikolayemrikh** [comment]
Подумаю над подключением пресетов

**Comment by zeckson** [comment]
Я так и не понял. Это уже закрытая ишья? Или ещё нет?

**Comment by nikolayemrikh** [comment]
Можно закрывать, твой запрос я выполнил
