### ISSUE TITLE
Expanded view is too noisy

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#40]
Given code:
```js
const name = `Кекс`;

const expected = {
  name: name,
  meow: function () {
    return `Мяу!`;
  }
};

const actual = {
  name, 
  meow() {
    return `Мяу!`;
  }
};

console.log(expected);
console.log(actual);
```

Given settings:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
  <script src="//htmlacademy.github.io/console.js/js/index-silent.js"></script>

</head>
<body>
  <script>  
  var settings = {
    object: {
      expandDepth: 1,
      showMethodBodyOnly: true,
      minFieldsToExpand: 1
    }
  };
  if (Array.isArray(window.jsConsolePresets)) {
    window.jsConsolePresets.push(settings);
  } else {
    window.jsConsolePresets = [settings];
  }
  </script>

</body>
</html>
```

In result I don't want to see extra field `__proto__` and object header (see red squares on screenshot):
![image](https://user-images.githubusercontent.com/259739/48262437-98092000-e433-11e8-9b60-65107fbbe747.png)

**Comment by nikolayemrikh** [comment]
You can specify in one of the param fields (or in common) `excludeProperties: [‘__proto__’]`

**Comment by nikolayemrikh** [comment]
you don’t want to see object header if it’s opened?

**Comment by zeckson** [comment]
> you don’t want to see object header if it’s opened?
It looks unnecessary in expanded object. Like doubling information.

**Comment by nikolayemrikh** [comment]
In Chrome was so for a long time

**Comment by nikolayemrikh** [comment]
But not in chrome there’re blank space if object opened. Looks weird

**Comment by nikolayemrikh** [comment]
Opened:

`{...}`
  field1: 1
  field2: 2

Closed:

`{field1: 2, field2: 2}`

You want like this?

**Comment by nikolayemrikh** [comment]
And use js/latest/ please ;)

**Comment by zeckson** [comment]
> You want like this?

Can we make it looks like JS-object?
closed
```
{field1: 2, field2: 2}
```
opened
```
{
  field1: 2, 
  field2: 2
}

**Comment by nikolayemrikh** [comment]
Even if we add curly braces to body, we need head to open it again. Blank head isn't a good idea imo.

**Comment by nikolayemrikh** [comment]
I deliberately got rid of these braces in body to make it looks like in google chrome console.

**Comment by nikolayemrikh** [comment]
> In result I don't want to see extra field __proto__
I lied, `excludeProperties` used to exlude in from autoexpand.

Do we need a config property to remove properties from object in result view? Or we need only to remove `__proto__`?

**Comment by nikolayemrikh** [comment]
Added `removeProperties` for this purpose. Renamed many config properties as well.

**Comment by zeckson** [comment]
> Even if we add curly braces to body, we need head to open it again. Blank head isn't a good idea imo.

Currently it looks really weird, please take look on screenshot. What are the options we have to make it more userfriendly and readable?

> Do we need a config property to remove properties from object in result view? Or we need only to remove __proto__?

Well, I don't know. I think in this particular case `excludeProperties: [‘__proto__’]` would be enough, I guess.

**Comment by nikolayemrikh** [comment]
I’ve pushed changes, take a look at them

**Comment by zeckson** [comment]
I don't see any attached commits or pull-requests. How can I do that?

**Comment by nikolayemrikh** [comment]
https://up.htmlacademy.ru/ecmascript/7/demos/1885#4

**Comment by nikolayemrikh** [comment]
Try to open objects there

**Comment by nikolayemrikh** [comment]
I’ve also changed read me and config’s property names

**Comment by zeckson** [comment]
Wow! Thanks! Looks nice! =)
![image](https://user-images.githubusercontent.com/259739/48337836-1acced80-e675-11e8-8de8-fc35099a11e4.png)
