### ISSUE TITLE
Опубликовать пакет в npm и в демках интенсивов подключать из unpkg.com

### ISSUE THREAD

**Issue by nikolayemrikh** [htmlacademy/console.js#46]
Вместо колхоза с github pages использовать https://unpkg.com/ и подключать либу в демках интенсивов одним из следующих образов:

Подключит версию `1.последняя_минорная.x`
```html
<script src="https://unpkg.com/@htmlacademy/console-js@^1"
```

Подключит последнюю версию
```html
<script src="https://unpkg.com/@htmlacademy/console-js"
```

@zeckson как думаешь? По-моему отличная идея

**Comment by meritt** [comment]
Плохая идея. Попробуйте решить всё-таки это тем, что держать это на наших серверах.

**Comment by nikolayemrikh** [comment]
@meritt я спрашивал про наши сервера, мне никто не ответил. Если дадите место, куда ее деплоить, будет отлично

**Comment by meritt** [comment]
@nikolayemrikh https://github.com/htmlacademy/content-server
